<?php return array (
  'Parisien\\VideosBundle\\Controller\\ConnectController' => '/data/www/leparisien/src/Parisien/VideosBundle/Controller/ConnectController.php',
  'Parisien\\VideosBundle\\Controller\\CommentController' => '/data/www/leparisien/src/Parisien/VideosBundle/Controller/CommentController.php',
  'Parisien\\MilibrisBundle\\Controller\\PopupController' => '/data/www/leparisien/src/Parisien/MilibrisBundle/Controller/PopupController.php',
  'Parisien\\MilibrisBundle\\DependencyInjection\\MilibrisExtension' => '/data/www/leparisien/src/Parisien/MilibrisBundle/DependencyInjection/MilibrisExtension.php',
  'Parisien\\MilibrisBundle\\DependencyInjection\\Configuration' => '/data/www/leparisien/src/Parisien/MilibrisBundle/DependencyInjection/Configuration.php',
  'Parisien\\MilibrisBundle\\MilibrisBundle' => '/data/www/leparisien/src/Parisien/MilibrisBundle/MilibrisBundle.php',
  'Parisien\\MilibrisBundle\\Command\\GetCatalogMilibrisCommand' => '/data/www/leparisien/src/Parisien/MilibrisBundle/Command/GetCatalogMilibrisCommand.php',
  'Parisien\\MilibrisBundle\\Util\\Requester' => '/data/www/leparisien/src/Parisien/MilibrisBundle/Util/Requester.php',
  'Parisien\\MilibrisBundle\\Util\\JsonRpcClient' => '/data/www/leparisien/src/Parisien/MilibrisBundle/Util/Milibris/JsonRpc/JsonRpcClient.php',
  'Parisien\\MilibrisBundle\\Util\\ApiConnector' => '/data/www/leparisien/src/Parisien/MilibrisBundle/Util/Milibris/ApiConnector.php',
  'Parisien\\Helper\\LeParisien\\ParisienHelper' => '/data/www/leparisien/src/Parisien/Helper/LeParisien/ParisienHelper.php',
  'Parisien\\Helper\\LeParisien\\Twig\\ParisienExtension' => '/data/www/leparisien/src/Parisien/Helper/LeParisien/Twig/ParisienExtension.php',
  'Parisien\\Helper\\LeParisien\\NavigationBranch' => '/data/www/leparisien/src/Parisien/Helper/LeParisien/NavigationBranch.php',
  'Parisien\\Helper\\LeParisien\\Loader' => '/data/www/leparisien/src/Parisien/Helper/LeParisien/Loader.php',
);